### PR TITLE
Address rootless-x11 cases

### LINKED ISSUE #1456: sddm-helper fails to take control of TTY
Since rebooting my PC today SDDM doesn't seem to successfully start sway or i3. I login, the greeter window disappears for a brief moment, and then it reappears.

I'm using the AUR `sddm-git` package, so I'm on latest `develop`, i.e. c7e8a9f212b3c929a52c01bac4aecfb823d6b878, and using Wayland. The theme is not of importance, I've tried without the theme, with the same result.

## SDDM Configuration
```
[~]$ cd /etc/sddm.conf.d/
[sddm.conf.d]$ ls -lisah
total 16K
2105347 4.0K drwxr-xr-x   2 root root 4.0K Oct 21 18:31 .
2097153 4.0K drwxr-xr-x 111 root root 4.0K Oct 21 18:30 ..
2098828 4.0K -rw-r--r--   1 root root   32 Sep 26 14:09 display-server.conf
2098855 4.0K -rw-r--r--   1 root root   28 Sep 26 13:56 theme.conf
[sddm.conf.d]$ cat display-server.conf
[General]
DisplayServer=wayland
[sddm.conf.d]$ cat theme.conf
[Theme]
Current=sugar-light
[sddm.conf.d]$
```
## Logs
```
-- Journal begins at Sun 2019-10-20 19:15:18 CEST, ends at Thu 2021-10-21 18:34:11 CEST. --
Oct 21 18:28:55 titan systemd[1]: Started Simple Desktop Display Manager.
Oct 21 18:28:55 titan sddm[16255]: Initializing...
Oct 21 18:28:55 titan sddm[16255]: Starting...
Oct 21 18:28:55 titan sddm[16255]: Logind interface found
Oct 21 18:28:55 titan sddm[16255]: Adding new display...
Oct 21 18:28:55 titan sddm[16255]: Loading theme configuration from ""
Oct 21 18:28:55 titan sddm[16255]: Using VT 7
Oct 21 18:28:55 titan sddm[16255]: Display server started.
Oct 21 18:28:55 titan sddm[16255]: Socket server starting...
Oct 21 18:28:55 titan sddm[16255]: Socket server started.
Oct 21 18:28:55 titan sddm[16255]: Loading theme configuration from ""
Oct 21 18:28:55 titan sddm[16255]: Greeter starting...
Oct 21 18:28:55 titan sddm-helper[16257]: [PAM] Starting...
Oct 21 18:28:55 titan sddm-helper[16257]: [PAM] Authenticating...
Oct 21 18:28:55 titan sddm-helper[16257]: pam_unix(sddm-greeter:session): session opened for user sddm(uid=971) by (uid=0)
Oct 21 18:28:55 titan sddm-helper[16257]: [PAM] returning.
Oct 21 18:28:56 titan sddm[16255]: Greeter session started successfully
Oct 21 18:28:57 titan sddm[16255]: Message received from greeter: Connect
Oct 21 18:29:01 titan sddm[16255]: Message received from greeter: Login
Oct 21 18:29:01 titan sddm[16255]: Reading from "/usr/share/wayland-sessions/sway.desktop"
Oct 21 18:29:01 titan sddm[16255]: Reading from "/usr/share/wayland-sessions/sway.desktop"
Oct 21 18:29:01 titan sddm[16255]: Session "/usr/share/wayland-sessions/sway.desktop" selected, command: "sway" for VT 7
Oct 21 18:29:01 titan sddm-helper[16321]: [PAM] Starting...
Oct 21 18:29:01 titan sddm-helper[16321]: [PAM] Authenticating...
Oct 21 18:29:01 titan sddm-helper[16321]: [PAM] Preparing to converse...
Oct 21 18:29:01 titan sddm-helper[16321]: [PAM] Conversation with 1 messages
Oct 21 18:29:01 titan sddm-helper[16321]: [PAM] returning.
Oct 21 18:29:01 titan sddm-helper[16321]: pam_systemd_home(sddm:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
Oct 21 18:29:01 titan sddm[16255]: Authenticated successfully
Oct 21 18:29:01 titan sddm-helper[16321]: pam_unix(sddm:session): session opened for user david(uid=1000) by (uid=0)
Oct 21 18:29:01 titan sddm-helper[16321]: pam_env(sddm:session): deprecated reading of user environment enabled
Oct 21 18:29:01 titan sddm-helper[16321]: Starting Wayland user session: "/usr/share/sddm/scripts/wayland-session sway"
Oct 21 18:29:01 titan sddm-helper[16322]: Failed to take control of /dev/tty7: Operation not permitted
Oct 21 18:29:01 titan sddm[16255]: Session started
Oct 21 18:29:01 titan sddm-helper[16321]: Could not fully finish the process "/usr/share/sddm/scripts/wayland-session"
Oct 21 18:29:01 titan sddm-helper[16321]: pam_unix(sddm:session): session closed for user david
Oct 21 18:29:01 titan sddm-helper[16321]: [PAM] Closing session
Oct 21 18:29:01 titan sddm-helper[16321]: [PAM] Ended.
Oct 21 18:29:01 titan sddm-helper[16325]: pam_unix(sddm-greeter:session): session opened for user sddm(uid=971) by (uid=0)
Oct 21 18:29:01 titan sddm[16255]: Auth: sddm-helper exited with 3
Oct 21 18:29:01 titan sddm[16255]: Greeter stopping...
Oct 21 18:29:01 titan sddm[16255]: Auth: sddm-helper exited with 255
Oct 21 18:29:01 titan sddm[16255]: Greeter stopped.
Oct 21 18:29:01 titan sddm[16255]: Socket server stopping...
Oct 21 18:29:01 titan sddm[16255]: Socket server stopped.
Oct 21 18:29:01 titan sddm[16255]: Removing display SDDM::Display(0x558497742320) ...
Oct 21 18:29:01 titan sddm[16255]: Adding new display...
Oct 21 18:29:01 titan sddm[16255]: Loading theme configuration from ""
Oct 21 18:29:01 titan sddm[16255]: Using VT 7
Oct 21 18:29:01 titan sddm[16255]: Display server started.
Oct 21 18:29:01 titan sddm[16255]: Socket server starting...
Oct 21 18:29:01 titan sddm[16255]: Socket server started.
Oct 21 18:29:01 titan sddm[16255]: Loading theme configuration from ""
Oct 21 18:29:01 titan sddm[16255]: Greeter starting...
Oct 21 18:29:01 titan sddm[16255]: Greeter starting...
Oct 21 18:29:01 titan sddm[16255]: QProcess: Destroyed while process ("/usr/lib/sddm/sddm-helper") is still running.
Oct 21 18:29:01 titan sddm-helper[16325]: [PAM] Starting...
Oct 21 18:29:01 titan sddm-helper[16325]: [PAM] Authenticating...
Oct 21 18:29:01 titan sddm-helper[16325]: [PAM] returning.
Oct 21 18:29:02 titan sddm[16255]: Greeter session started successfully
Oct 21 18:29:03 titan sddm[16255]: Message received from greeter: Connect
Oct 21 18:29:18 titan sddm[16255]: Message received from greeter: Login
Oct 21 18:29:18 titan sddm[16255]: Reading from "/usr/share/wayland-sessions/weston.desktop"
Oct 21 18:29:18 titan sddm[16255]: Reading from "/usr/share/wayland-sessions/weston.desktop"
Oct 21 18:29:18 titan sddm[16255]: Session "/usr/share/wayland-sessions/weston.desktop" selected, command: "weston" for VT 7
Oct 21 18:29:18 titan sddm-helper[16379]: [PAM] Starting...
Oct 21 18:29:18 titan sddm-helper[16379]: [PAM] Authenticating...
Oct 21 18:29:18 titan sddm-helper[16379]: [PAM] Preparing to converse...
Oct 21 18:29:18 titan sddm-helper[16379]: [PAM] Conversation with 1 messages
Oct 21 18:29:18 titan sddm-helper[16379]: [PAM] returning.
Oct 21 18:29:18 titan sddm[16255]: Authenticated successfully
Oct 21 18:29:18 titan sddm-helper[16379]: pam_systemd_home(sddm:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
Oct 21 18:29:18 titan sddm-helper[16379]: pam_unix(sddm:session): session opened for user david(uid=1000) by (uid=0)
Oct 21 18:29:18 titan sddm-helper[16379]: pam_env(sddm:session): deprecated reading of user environment enabled
Oct 21 18:29:18 titan sddm-helper[16379]: Starting Wayland user session: "/usr/share/sddm/scripts/wayland-session weston"
Oct 21 18:29:18 titan sddm-helper[16380]: Failed to take control of /dev/tty7: Operation not permitted
Oct 21 18:29:18 titan sddm[16255]: Session started
Oct 21 18:29:18 titan sddm-helper[16379]: Could not fully finish the process "/usr/share/sddm/scripts/wayland-session"
Oct 21 18:29:18 titan sddm-helper[16379]: pam_unix(sddm:session): session closed for user david
Oct 21 18:29:18 titan sddm-helper[16379]: [PAM] Closing session
Oct 21 18:29:18 titan sddm-helper[16379]: [PAM] Ended.
Oct 21 18:29:18 titan sddm-helper[16382]: pam_unix(sddm-greeter:session): session opened for user sddm(uid=971) by (uid=0)
Oct 21 18:29:18 titan sddm[16255]: Auth: sddm-helper exited with 3
Oct 21 18:29:18 titan sddm[16255]: Greeter stopping...
Oct 21 18:29:18 titan sddm[16255]: Auth: sddm-helper exited with 255
Oct 21 18:29:18 titan sddm[16255]: Greeter stopped.
Oct 21 18:29:18 titan sddm[16255]: Socket server stopping...
Oct 21 18:29:18 titan sddm[16255]: Socket server stopped.
Oct 21 18:29:18 titan sddm[16255]: Removing display SDDM::Display(0x558497756940) ...
Oct 21 18:29:18 titan sddm[16255]: Adding new display...
Oct 21 18:29:18 titan sddm[16255]: Loading theme configuration from ""
Oct 21 18:29:18 titan sddm[16255]: Using VT 7
Oct 21 18:29:18 titan sddm[16255]: Display server started.
Oct 21 18:29:18 titan sddm[16255]: Socket server starting...
Oct 21 18:29:18 titan sddm[16255]: Socket server started.
Oct 21 18:29:18 titan sddm[16255]: Loading theme configuration from ""
Oct 21 18:29:18 titan sddm[16255]: Greeter starting...
Oct 21 18:29:18 titan sddm[16255]: Greeter starting...
Oct 21 18:29:18 titan sddm[16255]: QProcess: Destroyed while process ("/usr/lib/sddm/sddm-helper") is still running.
Oct 21 18:29:18 titan sddm-helper[16382]: [PAM] Starting...
Oct 21 18:29:18 titan sddm-helper[16382]: [PAM] Authenticating...
Oct 21 18:29:18 titan sddm-helper[16382]: [PAM] returning.
Oct 21 18:29:18 titan sddm[16255]: Greeter session started successfully
Oct 21 18:29:19 titan sddm[16255]: Message received from greeter: Connect
Oct 21 18:29:29 titan sddm[16255]: Message received from greeter: Reboot
Oct 21 18:29:29 titan sddm[16255]: Error from greeter session: "Process crashed"
Oct 21 18:29:29 titan sddm[16255]: Auth: sddm-helper (--socket /tmp/sddm-auth8e8ac66b-8d91-4c94-b6bf-827d656966a0 --id 7 --start /usr/bin/sddm-greeter --socket /tmp/sddm--wPIgYh --user sddm --display-server weston --shell=fullscreen-shell.so --greeter) crashed (exit code 1)
Oct 21 18:29:29 titan sddm[16255]: Error from greeter session: "Process crashed"
Oct 21 18:29:29 titan sddm[16255]: Auth: sddm-helper exited with 1
Oct 21 18:29:29 titan sddm[16255]: Greeter stopped.
Oct 21 18:29:29 titan sddm[16255]: Signal received: SIGTERM
Oct 21 18:29:29 titan systemd[1]: Stopping Simple Desktop Display Manager...
Oct 21 18:29:29 titan sddm[16255]: Socket server stopping...
Oct 21 18:29:29 titan sddm[16255]: Socket server stopped.
Oct 21 18:29:29 titan systemd[1]: sddm.service: Deactivated successfully.
Oct 21 18:29:29 titan systemd[1]: Stopped Simple Desktop Display Manager.
```

Note the `Failed to take control of /dev/tty7: Operation not permitted`, which seems to be the underlying issue. I somewhat suspect that its related to the privilege dropping code, but that's purely a guess.

### PR DESCRIPTION
**Pull request by aleixpol**
The notable changes are:
* Stop the greeter before we start the new session
* Properly accounting for Xorg's -novtswitch
* Don't start a compositor after a session is closed, we were leaking them (x11-user & wayland)
* Improve debugging

Fixes https://github.com/sddm/sddm/issues/1456

### CODE REVIEW

**Comment by evelikov** [comment]
Coming from https://github.com/sddm/sddm/issues/1471#issuecomment-968331648 - two small requests:
 - considering this is considered a blocker, let's swap the "polish" with something more accurate
 - can you elaborate what kind rounds should we do - is there anything specific to look for?
 - non-rootful -> rootless is the more common term

File: src/common/MessageHandler.h [hunk 1]
```diff
@@ -75,6 +77,14 @@ namespace SDDM {
                 file.open(QFile::Truncate | QFile::WriteOnly);
         }
 
+        // If we can't open the file, create it in a writable location
```
Comment (evelikov) [inline src/common/MessageHandler.h:80]: For the non-QT experts, can you provide an inline example where this "writable location" might be?

File: src/helper/HelperSignalHandler.h [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+#ifndef HELPERSIGNALHANDLER_H
+#define HELPERSIGNALHANDLER_H
+
+#include <QCoreApplication>
+#include <signal.h>
+
+// ensure we exit gracefully and close the session if sigtermed (i.e restarting sddm)
+static void sigtermHandler(int signalNumber)
+{
+    Q_UNUSED(signalNumber)
```
Comment (evelikov) [inline src/helper/HelperSignalHandler.h]: ~~Both commit message and comment says "SIGTERM" yet we ignore the signal all together - SIGTERM or otherwise.~~
~~Why is that - can we tweak the comment to mention the reason?~~

Edit: brain fart - we get here only on SIGTERM, as seen in the `signal(SIGTERM, sigtermHandler)` line below

File: src/helper/UserSession.cpp [hunk 3]
```diff
@@ -100,17 +100,18 @@ namespace SDDM {
 
     void UserSession::stop()
```
Comment (evelikov) [inline src/helper/UserSession.cpp:101]: Silly question (last one I promise) - what's the problem with calling `terminate()`?

It seems that the more notable change is that we omit `waitForFinished()` will be blocking for potentially notable amount of time.

Comment (davidedmundson) [reply src/helper/UserSession.cpp:101]: we do still call terminate and waitForFinished() we've just wrapped things in an if statement.

**Comment by davidedmundson** [comment]
>can you elaborate what kind rounds should we do - is there anything specific to look for?

Every combo of:
autologin, root X11 greeter, rootless X11 greeter, wayland greeter
going into 
X11 session, Wayland session

including log out and going between them.

If you get anything explode or a black screen, it's not working great.

File: src/daemon/Display.cpp [hunk 4]
```diff
@@ -466,10 +467,6 @@ namespace SDDM {
         // greeter
         if (status != Auth::HELPER_AUTH_ERROR)
             stop();
-
-        // Start the greeter again as soon as the user session is closed
```
Comment (davidedmundson) [inline src/daemon/Display.cpp:470]: so what happens now when a user does log out in a root-full X session?

File: src/common/MessageHandler.h (hunk 1 above)
Comment (aleixpol) [reply src/common/MessageHandler.h:80]: You can test it yourself:
$ qtpaths --writable-path AppDataLocation
/home/apol/.local/share/<APPNAME>

File: src/daemon/Display.cpp (hunk 4 above)
Comment (aleixpol) [reply src/daemon/Display.cpp:470]: Display::stop gets called (right before the removal). This informs Seat that we've stooped and we go to Seat::displayStopped.

This removes the display and if it's display-less (which is the case as we just removed the display) it creates a new one which will start a new greeting process.

File: src/helper/UserSession.cpp (hunk 3 above)
Comment (evelikov) [reply src/helper/UserSession.cpp:101]: Right, I meant - what's the problem with calling `terminate()` and friends like `waitForFinished()`) in the `state() == QProcess::NotRunning` case?

File: src/common/MessageHandler.h (hunk 1 above)
Comment (evelikov) [reply src/common/MessageHandler.h:80]: Neat, can you add an inline example?

File: src/helper/UserSession.cpp (hunk 3 above)
Comment (aleixpol) [reply src/helper/UserSession.cpp:101]: We first call terminate which is more gentle, if terminate doesn't make the project finish, we kill it.

File: src/common/MessageHandler.h (hunk 1 above)
Comment (aleixpol) [reply src/common/MessageHandler.h:80]: Added examples on the comment.

File: src/common/CustomSignalHandler.cpp [hunk 5]
```diff
@@ -0,0 +1,60 @@
...
+
+#include "CustomSignalHandler.h"
+#include <QDebug>
+#include <signal.h>
+#include <sys/socket.h>
+#include <unistd.h>
+
+int CustomSignalHandler::signalFd[2];
+
+CustomSignalHandler::CustomSignalHandler()
```
Comment (davidedmundson) [inline src/common/CustomSignalHandler.cpp]: We also have src/daemon/SignalHandler.cpp:

which is near identical to this class. Only more verbose


We don't want both.
 
Can we either port:
src/daemon/DaemonApp.cpp:        connect(m_signalHandler, &SignalHandler::sigintReceived, this, &DaemonApp::quit);
src/daemon/DaemonApp.cpp:        connect(m_signalHandler, &SignalHandler::sigtermReceived, this, &DaemonApp::quit);

to this and drop SignalHandler.h or vice-versa.

Comment (aleixpol) [reply src/common/CustomSignalHandler.cpp]: Fair enough, added custom signal handling on the previous one so that we changed the least and moved it to common.

This class could use a cleanup, there's quite a bit of unneeded duplicate code as far as I understand, probably not for this MR though.

**Review by davidedmundson — APPROVED** [review]
