### PR TITLE
Fix user switching

### LINKED ISSUE #1642: User Switching workflow failure with SDDM on Wayland mode
It's a bit intricate because it's not entirely true that it's not working. It works when:

- user A: from the DE (e.g. Plasma) you ask to switch to a new user.
- you enter user B, ask for the same as the line before
- SDDM lists both A and B, log into either
- :bomb:

### PR DESCRIPTION
**Pull request by aleixpol**
Make sure we don't start a new session if we are switching. Update the terminalId (i.e. tty) Display property as we switch from the greeter to the actual session, as they might be on different terminals now.

~~WIP because we rely on Seat::displayStopped to choose the correct tty to jump to.~~

Fixes #1642

### CODE REVIEW

**Review by davidedmundson — APPROVED** [review]

**Review by davidedmundson — APPROVED** [review]

File: src/daemon/Display.cpp [hunk 1]
```diff
@@ -428,7 +427,7 @@ namespace SDDM {
         env.insert(QStringLiteral("XDG_SESSION_CLASS"), QStringLiteral("user"));
         env.insert(QStringLiteral("XDG_SESSION_TYPE"), session.xdgSessionType());
         env.insert(QStringLiteral("XDG_SEAT"), seat()->name());
-        env.insert(QStringLiteral("XDG_VTNR"), QString::number(terminalNewSession));
+        env.insert(QStringLiteral("XDG_VTNR"), QString::number(m_terminalId));
```
Comment (davidedmundson) [inline src/daemon/Display.cpp]: we don't want to lose track of which VT X11 is running on, they are separate things

Comment (aleixpol) [reply src/daemon/Display.cpp]: Addressed.

**Comment by smirkybg** [comment]
Not sure what you guys are fixing, but I suppose it's not my case.
If I login to user A, then choose "Switch User" from Plasma 5's lockscreen, I get to the SDDM session just fine.
Then if I login to user B, then logout, I get a black screen with a flashing cursor. I can switch the TTY manually, but this just doesn't work for me for years.

Using Wayland with Plasma 5 and sddm-git.
